Add metadata, support for relasing, package checks
Lightning-AI/lightning-GPT pull request #24
Opened 2023-01-05 11:07 UTC by justusschock

2023-01-05 13:53 UTC, lantiga requested changes
Pre-commit hooks shouldn't impact minGPT and nanoGPT (once it lands).

I propose to merge the nanoGPT PR, and update this one with the extra folder.

2023-01-05 13:53 UTC, lantiga commented on .pre-commit-config.yaml
> +  - repo: https://github.com/PyCQA/isort
can you make sure that we pre-commit hooks don't modify code in the nanogpt and mingpt directories?

2023-01-05 14:27 UTC, justusschock commented on mingpt/__init__.py
> +from mingpt.__about__ import *  # noqa: F401, F403
```suggestion
```

2023-01-06 10:48 UTC, justusschock commented on .pre-commit-config.yaml
> +  - repo: https://github.com/PyCQA/isort
done in #28

2023-01-06 11:15 UTC, lantiga approved these changes
Looks good, however let's decide on the name for the package.
I'm leaning towards `lightning-GPT` at this point. WDYT?

2023-01-06 12:28 UTC, merged